[workspace]
members = ["apps/*", "crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aloknigam/mdview"
rust-version = "1.75"

[workspace.dependencies]
comrak = "0.29"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
